### ISSUE TITLE
step by step install

### ISSUE THREAD

**Issue by toshibochan** [cwalk/Pi-Temp#1]
please you can add step by step installation.
i don't know how to use coding so usually i look step by step. if possible you can add installation file.

thanks

**Comment by toshibochan** [comment]
i did "sudo python lab_app.py" and come back:
lab_app.py:148: SyntaxWarning: import \* only allowed at module level
  @app.route("/to_plotly", methods=['GET'])  #This method will send the data to ploty.
Traceback (most recent call last):
  File "lab_app.py", line 47, in module
    from flask import Flask, request, render_template
ImportError: No module named flask

i need to install some thing? what is Flask?

**Comment by toshibochan** [comment]
i have this error now:lab_app.py:148: SyntaxWarning: import \* only allowed at module level
  @app.route("/to_plotly", methods=['GET'])  #This method will send the data to ploty.
Traceback (most recent call last):
  File "lab_app.py", line 50, in module
    import arrow
ImportError: No module named arrow

**Comment by cwalk** [comment]
Hey toshibochan, if you are not used to coding or don't know how to code, this might not be the best project for you. I would rate this as an intermediate level project for coding and Raspberry Pi knowledge. This was just more of me wanting to share a project I did, and I don't have step by step installation instructions available. 

Flask is a microframework for Python, and more info can be found here: http://flask.pocoo.org

Arrow is a Python library that offers a sensible, human-friendly approach to creating, manipulating, formatting and converting dates, times, and timestamps. It implements and updates the datetime type, plugging gaps in functionality, and provides an intelligent module API that supports many common creation scenarios. Simply put, it helps you work with dates and times with fewer imports and a lot less code. More can be read here: http://crsmithdev.com/arrow/
