### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by 2SeungHun** [cwalk/Pi-Temp#3]
With the release of the 3.0 version of Python, the print function '()' is essential.
Perhaps written in the previous version, without '()'.
I want to know the latest Python code Plz T.T

**Comment by ghost** [comment]
> With the release of the 3.0 version of Python, the print function '()' is essential.
> Perhaps written in the previous version, without '()'.
> I want to know the latest Python code Plz T.T

Just add parentheses, then.
such:
`print("Hello")`

**Comment by cwalk** [comment]
Correct, this was written in Python 2.7 I believe. You can easily Google the change in needed syntax to run with Python 3 like ghost provided.
