### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by logclinker** [cwalk/Pi-Temp#6]
Hi, i was wondering if there is an instruction on how to install the code on raspberry pi and set everything up. 
Video did not cover anything for installation.

Thanks.

**Comment by johnnynumber4** [comment]
@cwalk do you have install instructions?

**Comment by ensured** [comment]
foreal I'd love it if he or someone would include actual instructions to run the damn thing...

**Comment by cwalk** [comment]
https://www.udemy.com/course/rpi-full-stack/learn/lecture/3109350#overview

Can provide full instructions
