### ISSUE TITLE
Html error

### ISSUE THREAD

**Issue by MartinSokolov15** [cwalk/Pi-Temp#7]
This project is great! I have little problem. When i work on the html files, for example  lab_env_db.html, and run it on web browser (with install all programs in the list), i see it like pic part 1, but it should be like in pic part 2. Any help?
![92037625_1924719497658294_8241825688772935680_o](https://user-images.githubusercontent.com/64197840/80128649-a4892600-859e-11ea-8e31-f20e5924aa48.jpg)

**Comment by cwalk** [comment]
Apologies, it's been years since I wrote this program, so I don't remember the details (:
